### ISSUE TITLE
Custom HTML elements half-marked if containing existing HTML element

### ISSUE THREAD

**Issue by adamreisnz** [atom/language-html#123]
Custom HTML elements half-marked if their tag name contains the name of an existing HTML element.
At least, that seams to be the reason, e.g.:

``` html
<select-box
  options="simple"
  ng-model="model"
  on-change="updateModel(value)"
></select-box>
```

![image](https://cloud.githubusercontent.com/assets/490562/16366492/51cfb12e-3c6c-11e6-94a1-d161e99793b0.png)

Compare with for example:

``` html
<radio-buttons
  options="simple"
  ng-model="model"
  on-change="updateModel(value)"
></radio-buttons>
```

![image](https://cloud.githubusercontent.com/assets/490562/16366501/683c5b92-3c6c-11e6-885b-895832bc53cf.png)

The second part of the tag name `-box` is incorrectly marked as `entity.other.attribute-name.html`.

**Comment by 50Wliu** [comment]
I think I know the reason for this and it should be easy to fix.

**Comment by esdoppio** [comment]
Trying to fix this, found that the rules in question might need a rewrite.

The very first rule in the grammar:

```cson
  {
    'begin': '(<)([a-zA-Z0-9:-]++)(?=[^>]*></\\2>)'
    'beginCaptures':
      # …
    'end': '(>(\\s*<)/)(\\2)(>)'
    'endCaptures':
      # …
    'name': 'meta.tag.any.html'
    # …
  }
```

attempts to match a pair of tags in the same line without text in it, e.g., `<p></p>`, which is not useful in its own right, and it makes the result of tokenization somewhat unpredictable:

* `<p></p>` is tokenized as "meta.tag.any.html"
* `<p>\n\n</p>` or `<p>foo</p>` becomes "meta.tag.block.any.html"

The subsequent rules of tags categorize the tags into "structure", "block", "inline", and "other", which introduce some redundancies but not much value. I suggest we could use just 2 categories: "empty" (MUST NOT have a closing tag) and others (not necessarily named "other"). By that, we could tokenize invalid tags, e.g., `<style />`, `<img></img>` much easier.

**Comment by 50Wliu** [comment]
I have a few (old) PRs open that might solve this.  #93 in particular, though I think I still need to test if language-handlebars works correctly with that.

**Comment by JonathanWolfe** [comment]
I fixed this on my `language-polymer` via https://github.com/JonathanWolfe/language-polymer/commit/53991867e3d956c7f4249d519f214b2c22fb1eaa

**Comment by adambuczynski** [comment]
This now seems to be limited to cases where there is content present within the tags:

![image](https://cloud.githubusercontent.com/assets/490562/20278294/0541a536-ab09-11e6-908d-7512d0c3608d.png)

Or when the closing tags are on a new line:

![image](https://cloud.githubusercontent.com/assets/490562/20278309/166bc634-ab09-11e6-9c8c-9e89a3b96899.png)

**Comment by MoritzKn** [comment]
Just to clarify, #150 would fix this issue.

**Comment by adamreisnz** [comment]
This is still a problem with various tags:

![image](https://cloud.githubusercontent.com/assets/490562/26768294/fee3e46a-49fa-11e7-9b38-2c7fe3a5d40d.png)

**Comment by 50Wliu** [comment]
Yep.  Have not had a chance to review.  Will try to swing over and pay some attention to language-html soon.

**Comment by 50Wliu** [comment]
#150 has been merged.

![html-select-box](https://user-images.githubusercontent.com/2766036/30661293-d15f2ed0-9e43-11e7-8012-31c202224590.png)

**Comment by adamreisnz** [comment]
Awesome thanks!
