### ISSUE TITLE
"Toggle Comments" behaves incorrectly on script references.

### ISSUE THREAD

**Issue by jeffpamer** [atom/language-html#4]
Attempting to comment out a line with a script reference in the head of a document behaves strangely. It first attempts to comment out the line with two forward slashes. Toggle comments again then adds the correct html comments, but the forward slashes are still there. Activating toggle comments a third time removes the html comment but still leaves the forward slashes, you have to remove them manually.

**Comment by bcherny** [comment]
+1 this is really annoying, please push a fix

**Comment by jeffschwartz** [comment]
<b>Very problematic that this was fixed and now it is back again in v0.204.0. Please fix asap because it is a real pita.</b>

**Comment by cperryk** [comment]
+1 also seeing this issue again on 0.204.0

**Comment by mnquintana** [comment]
It's interesting that this issue disappeared for awhile, since no one actively fixed it. Was 0.203.0 the version that "fixed" this for people?

**Comment by lorenooliveira** [comment]
Still problematic on 0.027.0

**Comment by mixmatch** [comment]
Still broken in 0.209.0. Issue seems to relate to identification as embedded javascript code:
https://github.com/atom/language-html/blob/94e850dc4ab848baac1f413e4cb864864e1c24f8/grammars/html.cson#L216

**Comment by brunowego** [comment]
Still problematic on 1.0.0

**Comment by gamell** [comment]
+1 @brunowego

**Comment by mtt87** [comment]
+1 @brunowego

**Comment by khokhlachev** [comment]
it's very annoying bug! 1.0.0

**Comment by Robert-W** [comment]
Also having this issue on 1.0.0 in .js files, it's inserting html comments in js files.

**Comment by mtt87** [comment]
Okay it's definitely the latest version of Emmet that's breaking up things.

As workaround disable Emmet comment in Settings > Packages > Emmet:
![screen shot 2015-06-29 at 21 09 46](https://cloud.githubusercontent.com/assets/2150927/8417274/4e0068d2-1ea3-11e5-9009-c85fbc072193.png)

**Comment by TheSuperFly** [comment]
@mtt87 so at the end this solution worked. But that means that's not a problem from language-html but emmet package, nah?

**Comment by mnquintana** [comment]
@TheSuperFly @mtt87 @Robert-W Let's keep this on topic – what you're describing is a separate issue from the one reported in this issue.

**Comment by benogle** [comment]
A fix for this will be out in atom 1.0.4

**Comment by Benjamski** [comment]
Was this ever officially fixed?

```html
<li> <a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
{{!-- <li> <a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li> --}}
```

This is what happens when I use CMD + / in Atom. It's a minor issue but really annoying one. This is the only issue addressing it I could find, but please redirect me if I missed a more recent one.
